[config]
model = "gemini/gemini-3.6-flash"
fallback_models = ["gemini/gemini-3.5-flash", "gemini/gemini-2.5-flash", "gemini/gemini-2.0-flash", "gemini/gemini-3.1-pro"]
restricted_mode = true

[github_app]
pr_commands = [
    "/describe",
    "/improve",
    "/review"
]

[github_action_config]
auto_review = true
auto_describe = true
auto_improve = true
handle_push_trigger = true
push_commands = [
    "/review",
    "/improve"
]

[pr_description]
generate_ai_title = true

[pr_reviewer]
num_max_findings = 20
require_score_review = true
require_tests_review = true

[pr_code_suggestions]
num_code_suggestions_per_chunk = 8
commitable_code_suggestions = true
