#!/usr/bin/env python3
"""
Composites the raw emulator captures into the Play Store listing images.

Reads scenes.json (what each store image shows, in store order) and theme.json (how every image
looks), builds one HTML page per scene from template.html and style.css, rasterises it with
headless Chrome at the canvas size, verifies the result is what Play accepts (the canvas size,
8-bit RGB, no alpha channel, 2 to 8 images), writes it to the output directory as NN-<id>.png,
rewrites the README block between the store-screenshots markers and writes a review page.

A raw capture is never modified: each store image is a new file rasterised from the page, so
deleting the output and re-running reproduces it. Python standard library only; Chrome is the
only external program.

Usage: render.py [options]
  --raw DIR        captures, <capture>.png (default screenshots/raw)
  --out DIR        store images (default screenshots/readme)
  --scenes FILE    scene list (default scenes.json beside this script)
  --theme FILE     theme (default theme.json beside this script)
  --readme FILE    README whose marker block is rewritten (default README.md; - skips it)
  --preview FILE   review page (default screenshots/preview.html; - skips it)
  --work-dir DIR   pages and Chrome's output (default upgrade-test-out/store-screenshots/render)
  --only a,b       render these scenes only; the README and preview are written only when every
                   scene's image exists
  --chrome PATH    Chrome binary (default $STORE_SCREENSHOTS_CHROME, the macOS app, or
                   google-chrome / chromium on PATH)

Relative paths are resolved against the repository root, so the script works from any directory.
"""
import argparse
import html
import json
import os
import re
import shutil
import struct
import subprocess
import sys
import zlib
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]

README_START = "<!-- store-screenshots:start -->"
README_END = "<!-- store-screenshots:end -->"
README_NOTE = (
    "<!-- Generated by scripts/store-screenshots/render.py from scenes.json; "
    "edit that file and re-run, not this block. -->"
)
# Play accepts between two and eight phone screenshots per listing.
MIN_SCENES = 2
MAX_SCENES = 8
SCENE_ID = re.compile(r"^[a-z0-9_]+$")
CAPTURE_NAME = re.compile(r"^[A-Za-z0-9_-]+$")
OUTPUT_NAME = re.compile(r"^\d{2}-[a-z0-9_]+\.png$")
CHROME_TIMEOUT_S = 120
# Chrome's screenshot is taken when the page is idle or this much virtual time has passed, so
# fonts and images referenced by the page are loaded before the frame is captured.
VIRTUAL_TIME_BUDGET_MS = 5000
CHROME_CANDIDATES = (
    "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
    "/Applications/Chromium.app/Contents/MacOS/Chromium",
)
CHROME_ON_PATH = ("google-chrome", "google-chrome-stable", "chromium", "chromium-browser")

PNG_SIGNATURE = b"\x89PNG\r\n\x1a\n"
PNG_RGB = 2
PNG_RGBA = 6


class RenderError(Exception):
    """A problem the user has to fix: bad input, a missing capture, output Play would reject."""


# --- small helpers -----------------------------------------------------------------------------

def resolve(path):
    """A path from the command line, relative to the repository root unless absolute."""
    path = Path(path)
    return path if path.is_absolute() else ROOT / path


def load_json(path, what):
    try:
        with open(path, encoding="utf-8") as handle:
            return json.load(handle)
    except OSError as error:
        raise RenderError("cannot read %s %s: %s" % (what, path, error)) from error
    except ValueError as error:
        raise RenderError("%s %s is not valid JSON: %s" % (what, path, error)) from error


def expect(condition, message):
    if not condition:
        raise RenderError(message)


def number(value):
    return isinstance(value, (int, float)) and not isinstance(value, bool)


def css_length(value):
    """A theme number as a CSS pixel length, or a string as written (e.g. "-0.02em")."""
    if number(value):
        return "%gpx" % value
    return str(value)


# --- PNG --------------------------------------------------------------------------------------

def png_chunks(data):
    """Yields (type, body) for every chunk of a PNG file held in memory."""
    expect(data[:8] == PNG_SIGNATURE, "not a PNG file")
    pos = 8
    while pos + 8 <= len(data):
        length, kind = struct.unpack(">I4s", data[pos:pos + 8])
        yield kind, data[pos + 8:pos + 8 + length]
        pos += 12 + length


def png_info(path):
    """
    Reads a PNG header without decoding the image.

    @return (width, height, bit depth, colour type, interlace method)
    """
    try:
        with open(path, "rb") as handle:
            head = handle.read(33)
    except OSError as error:
        raise RenderError("cannot read %s: %s" % (path, error)) from error
    expect(head[:8] == PNG_SIGNATURE and head[12:16] == b"IHDR", "%s is not a PNG file" % path)
    width, height, depth, colour, _, _, interlace = struct.unpack(">IIBBBBB", head[16:29])
    return width, height, depth, colour, interlace


def unfilter_row(filter_type, row, previous, bpp):
    """
    Reverses one PNG scanline filter in place (PNG specification, section 9).

    @param filter_type 0..4 as stored in the scanline's first byte
    @param row the filtered bytes of this scanline, reconstructed in place
    @param previous the reconstructed bytes of the scanline above (zeros for the first)
    @param bpp bytes per pixel
    """
    if filter_type == 0:
        return
    if filter_type == 1:
        for i in range(bpp, len(row)):
            row[i] = (row[i] + row[i - bpp]) & 0xFF
    elif filter_type == 2:
        row[:] = bytes(map(lambda cur, up: (cur + up) & 0xFF, row, previous))
    elif filter_type == 3:
        for i in range(len(row)):
            left = row[i - bpp] if i >= bpp else 0
            row[i] = (row[i] + ((left + previous[i]) >> 1)) & 0xFF
    elif filter_type == 4:
        for i in range(len(row)):
            if i >= bpp:
                left = row[i - bpp]
                upper_left = previous[i - bpp]
            else:
                left = upper_left = 0
            up = previous[i]
            estimate = left + up - upper_left
            d_left = abs(estimate - left)
            d_up = abs(estimate - up)
            d_upper_left = abs(estimate - upper_left)
            if d_left <= d_up and d_left <= d_upper_left:
                predictor = left
            elif d_up <= d_upper_left:
                predictor = up
            else:
                predictor = upper_left
            row[i] = (row[i] + predictor) & 0xFF
    else:
        raise RenderError("unknown PNG filter type %d" % filter_type)


def png_chunk(kind, body):
    return struct.pack(">I", len(body)) + kind + body + struct.pack(">I", zlib.crc32(kind + body) & 0xFFFFFFFF)


def strip_alpha(source, target):
    """
    Rewrites an 8-bit RGBA PNG as 8-bit RGB, dropping the alpha channel.

    Chrome writes an RGB file when the page is opaque, so this is the fallback for the case where
    it does not; Play rejects images with an alpha channel. Each output scanline uses the Sub
    filter, which is cheap to compute and keeps gradients compressible.
    """
    data = source.read_bytes()
    width, height, depth, colour, interlace = png_info(source)
    expect(depth == 8 and colour == PNG_RGBA, "%s is not an 8-bit RGBA PNG" % source)
    expect(interlace == 0, "%s is interlaced, which this script does not decode" % source)
    raw = zlib.decompress(b"".join(body for kind, body in png_chunks(data) if kind == b"IDAT"))
    stride = width * 4
    expect(len(raw) == height * (stride + 1), "%s has a truncated image stream" % source)
    previous = bytearray(stride)
    filtered = bytearray()
    pos = 0
    for _ in range(height):
        row = bytearray(raw[pos + 1:pos + 1 + stride])
        unfilter_row(raw[pos], row, previous, 4)
        pos += 1 + stride
        rgb = bytearray(width * 3)
        rgb[0::3] = row[0::4]
        rgb[1::3] = row[1::4]
        rgb[2::3] = row[2::4]
        sub = bytearray(rgb)
        sub[3:] = bytes(map(lambda cur, left: (cur - left) & 0xFF, rgb[3:], rgb[:-3]))
        filtered.append(1)
        filtered += sub
        previous = row
    header = struct.pack(">IIBBBBB", width, height, 8, PNG_RGB, 0, 0, 0)
    target.write_bytes(
        PNG_SIGNATURE
        + png_chunk(b"IHDR", header)
        + png_chunk(b"IDAT", zlib.compress(bytes(filtered), 9))
        + png_chunk(b"IEND", b""),
    )


# --- inputs -----------------------------------------------------------------------------------

class Frame:
    """
    A device frame from Android Studio's device-art-resources: back.webp (the device, screen area
    transparent), mask.webp (the overlay that paints the screen's rounded corners and camera
    cutout over the capture) and the `layout` text file that places the screen inside the back.
    """

    def __init__(self, directory):
        self.directory = directory
        expect(directory.is_dir(), "frame directory %s does not exist" % directory)
        self.back = directory / "back.webp"
        self.mask = directory / "mask.webp"
        layout = directory / "layout"
        for required in (self.back, self.mask, layout):
            expect(required.is_file(), "frame %s is missing %s" % (directory.name, required.name))
        text = layout.read_text(encoding="utf-8")
        display = re.search(r"display\s*\{\s*width\s+(\d+)\s+height\s+(\d+)", text)
        size = re.search(r"portrait\s*\{\s*width\s+(\d+)\s+height\s+(\d+)", text)
        offset = re.search(r"name\s+device\s+x\s+(\d+)\s+y\s+(\d+)", text)
        expect(display and size and offset, "frame %s has a layout file this script cannot read" % directory.name)
        self.screen_width, self.screen_height = int(display.group(1)), int(display.group(2))
        self.width, self.height = int(size.group(1)), int(size.group(2))
        self.screen_left, self.screen_top = int(offset.group(1)), int(offset.group(2))


class Theme:
    """theme.json, validated: every visual decision the template makes comes from here."""

    def __init__(self, path):
        self.path = path
        data = load_json(path, "theme")
        where = "theme %s" % path.name
        canvas = self.section(data, "canvas", where)
        self.width = self.integer(canvas, "width", where + ": canvas")
        self.height = self.integer(canvas, "height", where + ": canvas")
        expect(isinstance(data.get("frame"), str), where + ": frame must name a directory under frames/")
        self.frame = Frame(HERE / "frames" / data["frame"])
        font = self.section(data, "font", where)
        expect(isinstance(font.get("family"), str) and font["family"], where + ": font.family must be a name")
        self.font_family = font["family"]
        files = font.get("files")
        expect(isinstance(files, list) and files, where + ": font.files must list at least one file")
        self.font_files = []
        for entry in files:
            expect(isinstance(entry, dict) and isinstance(entry.get("path"), str), where + ": each font file needs a path")
            file_path = HERE / entry["path"]
            expect(file_path.is_file(), where + ": font file %s does not exist" % file_path)
            self.font_files.append((file_path, str(entry.get("weight", "400")), str(entry.get("format", "truetype"))))
        background = self.section(data, "background", where)
        expect(isinstance(background.get("fill"), str), where + ": background.fill must be a CSS background")
        self.background_fill = background["fill"]
        self.shapes = []
        for index, shape in enumerate(background.get("shapes", [])):
            label = where + ": background.shapes[%d]" % index
            expect(isinstance(shape, dict), label + " must be an object")
            self.shapes.append({
                "left": self.integer(shape, "left", label),
                "top": self.integer(shape, "top", label),
                "size": self.integer(shape, "size", label),
                "fill": self.text(shape, "fill", label),
            })
        copy = self.section(data, "copy", where)
        self.copy_top = self.integer(copy, "top", where + ": copy")
        self.copy_inset = self.integer(copy, "sideInset", where + ": copy")
        self.copy_align = self.text(copy, "align", where + ": copy")
        self.headline = self.text_style(self.section(copy, "headline", where + ": copy"), where + ": copy.headline")
        self.subhead = self.text_style(self.section(copy, "subhead", where + ": copy"), where + ": copy.subhead")
        self.subhead["gap"] = self.integer(copy["subhead"], "gap", where + ": copy.subhead")
        phone = self.section(data, "phone", where)
        self.phone_shadow = self.text(phone, "shadow", where + ": phone")
        layouts = self.section(data, "layouts", where)
        expect(layouts, where + ": layouts must define at least one layout")
        self.layouts = {}
        for name, slots in layouts.items():
            label = where + ": layouts.%s" % name
            expect(isinstance(slots, list) and slots, label + " must be a list of phone slots")
            parsed = []
            for index, slot in enumerate(slots):
                slot_label = "%s[%d]" % (label, index)
                expect(isinstance(slot, dict), slot_label + " must be an object")
                scale = slot.get("scale", 1)
                rotate = slot.get("rotate", 0)
                clip = slot.get("clip")
                expect(number(scale) and scale > 0, slot_label + ".scale must be a positive number")
                expect(number(rotate), slot_label + ".rotate must be a number of degrees")
                # A clip keeps only part of the phone: a polygon in percent of the footprint, so two
                # slots at the same position with complementary clips show one phone split between
                # two captures. Points may lie outside 0..100 so the drop shadow is not cut off.
                expect(clip is None or (isinstance(clip, list) and len(clip) >= 3 and all(
                    isinstance(point, list) and len(point) == 2 and all(number(value) for value in point)
                    for point in clip)),
                    slot_label + ".clip must be a list of at least three [x, y] points, in percent of the footprint")
                parsed.append({
                    "left": self.integer(slot, "left", slot_label),
                    "top": self.integer(slot, "top", slot_label),
                    "scale": scale,
                    "rotate": rotate,
                    "clip": clip,
                })
            self.layouts[name] = parsed

    @staticmethod
    def section(data, key, where):
        value = data.get(key)
        expect(isinstance(value, dict), "%s: %s must be an object" % (where, key))
        return value

    @staticmethod
    def integer(data, key, where):
        value = data.get(key)
        expect(number(value), "%s.%s must be a number" % (where, key))
        return value

    @staticmethod
    def text(data, key, where):
        value = data.get(key)
        expect(isinstance(value, str) and value, "%s.%s must be a non-empty string" % (where, key))
        return value

    def text_style(self, data, where):
        return {
            "size": self.integer(data, "size", where),
            "weight": self.integer(data, "weight", where),
            "lineHeight": self.integer(data, "lineHeight", where),
            "letterSpacing": css_length(data.get("letterSpacing", "0")),
            "color": self.text(data, "color", where),
        }


class Scene:
    """One store image: its copy, its layout and the captures that fill the layout's slots."""

    def __init__(self, index, data, theme, where):
        expect(isinstance(data, dict), where + " must be an object")
        self.index = index
        self.id = data.get("id")
        expect(isinstance(self.id, str) and SCENE_ID.match(self.id), where + ": id must match %s" % SCENE_ID.pattern)
        where = "scene %s" % self.id
        self.layout_name = data.get("layout")
        expect(self.layout_name in theme.layouts, "%s: layout %r is not defined in %s (have %s)" % (
            where, self.layout_name, theme.path.name, ", ".join(sorted(theme.layouts))))
        self.slots = theme.layouts[self.layout_name]
        self.captures = data.get("captures")
        expect(isinstance(self.captures, list) and all(isinstance(c, str) and CAPTURE_NAME.match(c) for c in self.captures),
               where + ": captures must be a list of capture names")
        expect(len(self.captures) == len(self.slots), "%s: layout %s has %d slot(s) but %d capture(s) are listed" % (
            where, self.layout_name, len(self.slots), len(self.captures)))
        self.headline = data.get("headline")
        expect(isinstance(self.headline, str) and self.headline.strip(), where + ": headline must be a non-empty string")
        self.subhead = data.get("subhead", "")
        expect(isinstance(self.subhead, str), where + ": subhead must be a string")
        self.output_name = "%02d-%s.png" % (index, self.id)

    @property
    def alt_text(self):
        return " ".join(self.headline.split())


class Scenes:
    """scenes.json, validated against the theme it will be rendered with."""

    def __init__(self, path, theme):
        data = load_json(path, "scenes")
        where = "scenes %s" % path.name
        entries = data.get("scenes") if isinstance(data, dict) else None
        expect(isinstance(entries, list), where + ": top-level object needs a scenes list")
        expect(MIN_SCENES <= len(entries) <= MAX_SCENES, "%s: Play accepts %d to %d phone screenshots, %d are listed" % (
            where, MIN_SCENES, MAX_SCENES, len(entries)))
        self.scenes = [Scene(i + 1, entry, theme, "%s: scenes[%d]" % (where, i)) for i, entry in enumerate(entries)]
        ids = [scene.id for scene in self.scenes]
        expect(len(set(ids)) == len(ids), where + ": scene ids must be unique")
        readme = data.get("readme", {})
        expect(isinstance(readme, dict), where + ": readme must be an object")
        self.readme_columns = readme.get("columns", 3)
        self.readme_width = readme.get("width", 200)
        expect(isinstance(self.readme_columns, int) and self.readme_columns >= 1, where + ": readme.columns must be a positive integer")
        expect(isinstance(self.readme_width, int) and self.readme_width >= 1, where + ": readme.width must be a positive integer")

    def __iter__(self):
        return iter(self.scenes)


# --- page -------------------------------------------------------------------------------------

def file_url(path):
    return Path(path).resolve().as_uri()


def font_faces(theme):
    faces = []
    for path, weight, fmt in theme.font_files:
        faces.append(
            '@font-face { font-family: "%s"; src: url("%s") format("%s"); font-weight: %s; font-display: block; }'
            % (theme.font_family, file_url(path), fmt, weight)
        )
    return "\n".join(faces)


def css_variables(theme):
    variables = {
        "canvas-width": css_length(theme.width),
        "canvas-height": css_length(theme.height),
        "background": theme.background_fill,
        "font-family": '"%s"' % theme.font_family,
        "copy-top": css_length(theme.copy_top),
        "copy-inset": css_length(theme.copy_inset),
        "copy-align": theme.copy_align,
        "headline-size": css_length(theme.headline["size"]),
        "headline-weight": "%g" % theme.headline["weight"],
        "headline-line-height": "%g" % theme.headline["lineHeight"],
        "headline-letter-spacing": theme.headline["letterSpacing"],
        "headline-color": theme.headline["color"],
        "subhead-size": css_length(theme.subhead["size"]),
        "subhead-weight": "%g" % theme.subhead["weight"],
        "subhead-line-height": "%g" % theme.subhead["lineHeight"],
        "subhead-letter-spacing": theme.subhead["letterSpacing"],
        "subhead-color": theme.subhead["color"],
        "subhead-gap": css_length(theme.subhead["gap"]),
        "phone-shadow": theme.phone_shadow,
    }
    return "\n".join("  --%s: %s;" % item for item in variables.items())


def copy_html(text):
    """Headline or subhead text as HTML: escaped, with hand-placed line breaks."""
    return "<br>".join(html.escape(line.strip()) for line in text.split("\n"))


def shapes_html(theme):
    return "\n".join(
        '<div class="shape" style="left:%gpx;top:%gpx;width:%gpx;height:%gpx;background:%s"></div>'
        % (shape["left"], shape["top"], shape["size"], shape["size"], html.escape(shape["fill"], quote=True))
        for shape in theme.shapes
    )


def phone_html(slot, capture, frame):
    """
    One framed phone. The outer box is the phone's scaled footprint, rotated about its own
    centre so a tilt in the theme reads as a tilt of the phone; inside it, the device-art is laid
    out at its native size and scaled from the top-left corner: capture, then the corner-and-cutout
    overlay, then the frame on top. A slot's clip becomes a clip-path on the box; CSS applies it
    after the drop shadow and before the rotation, so the seam tilts with the phone.
    """
    scale = slot["scale"]
    screen = 'left:%dpx;top:%dpx;width:%dpx;height:%dpx' % (
        frame.screen_left, frame.screen_top, frame.screen_width, frame.screen_height)
    clip = ""
    if slot["clip"]:
        clip = ";clip-path:polygon(%s)" % ", ".join("%g%% %g%%" % (x, y) for x, y in slot["clip"])
    return (
        '<div class="phone" style="left:%gpx;top:%gpx;width:%gpx;height:%gpx;transform:rotate(%gdeg)%s">\n'
        '  <div class="device" style="width:%dpx;height:%dpx;transform:scale(%g)">\n'
        '    <img class="screen" src="%s" style="%s">\n'
        '    <img class="cover" src="%s" style="%s">\n'
        '    <img class="frame" src="%s" style="width:%dpx;height:%dpx">\n'
        '  </div>\n'
        '</div>'
    ) % (
        slot["left"], slot["top"], frame.width * scale, frame.height * scale, slot["rotate"], clip,
        frame.width, frame.height, scale,
        file_url(capture), screen,
        file_url(frame.mask), screen,
        file_url(frame.back), frame.width, frame.height,
    )


def build_page(scene, theme, raw_dir, template, style):
    phones = "\n".join(phone_html(slot, raw_dir / (capture + ".png"), theme.frame)
                       for slot, capture in zip(scene.slots, scene.captures))
    subhead = '<p class="subhead">%s</p>' % copy_html(scene.subhead) if scene.subhead.strip() else ""
    page = template
    for key, value in (
        ("title", html.escape(scene.alt_text)),
        ("font_faces", font_faces(theme)),
        ("css_variables", css_variables(theme)),
        ("style", style),
        ("shapes", shapes_html(theme)),
        ("headline", copy_html(scene.headline)),
        ("subhead", subhead),
        ("phones", phones),
    ):
        page = page.replace("{{%s}}" % key, value)
    leftover = re.search(r"\{\{[a-z_]+\}\}", page)
    expect(leftover is None, "template.html has an unknown placeholder %s" % (leftover.group(0) if leftover else ""))
    return page


# --- Chrome -----------------------------------------------------------------------------------

def find_chrome(explicit):
    candidates = [explicit, os.environ.get("STORE_SCREENSHOTS_CHROME")]
    candidates += list(CHROME_CANDIDATES)
    candidates += [shutil.which(name) for name in CHROME_ON_PATH]
    for candidate in candidates:
        if candidate and Path(candidate).is_file():
            return candidate
    raise RenderError("no Chrome found; pass --chrome or set STORE_SCREENSHOTS_CHROME to the binary")


def rasterise(chrome, page, output, theme, profile_dir):
    command = [
        chrome,
        "--headless=new",
        "--hide-scrollbars",
        "--disable-gpu",
        "--no-first-run",
        "--disable-extensions",
        "--allow-file-access-from-files",
        "--force-device-scale-factor=1",
        "--virtual-time-budget=%d" % VIRTUAL_TIME_BUDGET_MS,
        "--user-data-dir=%s" % profile_dir,
        "--window-size=%d,%d" % (theme.width, theme.height),
        "--screenshot=%s" % output,
        file_url(page),
    ]
    if hasattr(os, "geteuid") and os.geteuid() == 0:
        # Chrome refuses to start its sandbox as root, which is how Linux containers run it.
        command.insert(1, "--no-sandbox")
    if output.exists():
        output.unlink()
    try:
        result = subprocess.run(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=CHROME_TIMEOUT_S)
    except subprocess.TimeoutExpired as error:
        raise RenderError("Chrome did not finish %s within %d s" % (page.name, CHROME_TIMEOUT_S)) from error
    if result.returncode != 0 or not output.is_file():
        raise RenderError("Chrome failed on %s (exit %d):\n%s" % (
            page.name, result.returncode, result.stderr.decode("utf-8", "replace").strip()))


# --- outputs ----------------------------------------------------------------------------------

def verify_store_image(path, theme):
    """Fails unless the file is exactly what Play accepts and the theme promised."""
    width, height, depth, colour, _ = png_info(path)
    expect((width, height) == (theme.width, theme.height),
           "%s is %dx%d, expected %dx%d" % (path.name, width, height, theme.width, theme.height))
    expect(depth == 8, "%s has a bit depth of %d, expected 8" % (path.name, depth))
    expect(colour == PNG_RGB, "%s has colour type %d, expected %d (RGB without alpha)" % (path.name, colour, PNG_RGB))


def readme_block(scenes, out_dir, readme_path):
    prefix = os.path.relpath(out_dir, readme_path.parent).replace(os.sep, "/")
    images = [
        '<img src="./%s/%s" alt="%s" width="%d">' % (
            prefix, scene.output_name, html.escape(scene.alt_text, quote=True), scenes.readme_width)
        for scene in scenes
    ]
    rows = ["&emsp;".join(images[i:i + scenes.readme_columns]) for i in range(0, len(images), scenes.readme_columns)]
    return "\n".join([README_START, README_NOTE, ""] + ["%s\n" % row for row in rows] + [README_END])


def update_readme(readme_path, block):
    try:
        text = readme_path.read_text(encoding="utf-8")
    except OSError as error:
        raise RenderError("cannot read %s: %s" % (readme_path, error)) from error
    start = text.find(README_START)
    end = text.find(README_END)
    expect(start >= 0 and end > start, "%s has no %s ... %s block to rewrite" % (readme_path, README_START, README_END))
    updated = text[:start] + block + text[end + len(README_END):]
    if updated != text:
        readme_path.write_text(updated, encoding="utf-8")
        return True
    return False


def preview_page(scenes, theme, raw_dir, out_dir, preview_path):
    def rel(path):
        return os.path.relpath(path, preview_path.parent).replace(os.sep, "/")

    sections = []
    for scene in scenes:
        raws = "".join(
            '<figure><img src="%s" width="135"><figcaption>%s</figcaption></figure>' % (rel(raw_dir / (c + ".png")), c)
            for c in scene.captures
        )
        sections.append(
            '<section>\n<h2>%s</h2>\n<p class="copy">%s<br><small>%s</small></p>\n<p class="meta">layout %s</p>\n'
            '<div class="row"><figure class="store"><img src="%s" width="360"><figcaption>%s</figcaption></figure>%s</div>\n'
            '</section>' % (
                scene.output_name, html.escape(scene.alt_text), html.escape(" ".join(scene.subhead.split())),
                scene.layout_name, rel(out_dir / scene.output_name), scene.output_name, raws)
        )
    page = (
        "<!doctype html>\n<html lang=\"en\"><head><meta charset=\"utf-8\"><title>Store screenshots</title>\n<style>\n"
        "body{margin:0;padding:24px;background:#15171a;color:#e6e6e6;font:14px/1.4 -apple-system,Helvetica,Arial,sans-serif}\n"
        "h1{font-size:20px;margin:0 0 16px} h2{font-size:16px;margin:0 0 4px} section{padding:16px 0;border-top:1px solid #2a2d31}\n"
        ".copy{margin:0 0 4px;font-size:15px} .meta{margin:0 0 10px;color:#9aa0a6}\n"
        ".row{display:flex;gap:16px;align-items:flex-start} figure{margin:0;text-align:center;color:#9aa0a6;font-size:12px}\n"
        "img{display:block;border-radius:8px;background:#000} .store img{box-shadow:0 8px 24px rgba(0,0,0,.5)}\n"
        "</style></head><body>\n<h1>Store screenshots &mdash; theme %s, %d scene(s)</h1>\n%s\n</body></html>\n"
        % (html.escape(theme.path.name), len(scenes.scenes), "\n".join(sections))
    )
    preview_path.parent.mkdir(parents=True, exist_ok=True)
    preview_path.write_text(page, encoding="utf-8")


def remove_stale_outputs(out_dir, expected):
    """Deletes numbered store images a previous run wrote that this scene list no longer produces."""
    for existing in sorted(out_dir.glob("*.png")):
        if OUTPUT_NAME.match(existing.name) and existing.name not in expected:
            existing.unlink()
            print("removed stale %s" % existing.name)


# --- main -------------------------------------------------------------------------------------

def parse_args(argv):
    parser = argparse.ArgumentParser(description="Composite raw captures into Play Store listing images.")
    parser.add_argument("--raw", default="screenshots/raw")
    parser.add_argument("--out", default="screenshots/readme")
    parser.add_argument("--scenes", default=str(HERE / "scenes.json"))
    parser.add_argument("--theme", default=str(HERE / "theme.json"))
    parser.add_argument("--readme", default="README.md")
    parser.add_argument("--preview", default="screenshots/preview.html")
    parser.add_argument("--work-dir", default="upgrade-test-out/store-screenshots/render")
    parser.add_argument("--only", default="")
    parser.add_argument("--chrome", default=None)
    return parser.parse_args(argv)


def run(args):
    theme = Theme(resolve(args.theme))
    scenes = Scenes(resolve(args.scenes), theme)
    raw_dir = resolve(args.raw)
    out_dir = resolve(args.out)
    work_dir = resolve(args.work_dir)
    chrome = find_chrome(args.chrome)
    template = (HERE / "template.html").read_text(encoding="utf-8")
    style = (HERE / "style.css").read_text(encoding="utf-8")

    wanted = [part.strip() for part in args.only.split(",") if part.strip()]
    known = {scene.id for scene in scenes}
    unknown = sorted(set(wanted) - known)
    expect(not unknown, "--only names unknown scene(s) %s; scenes.json has %s" % (", ".join(unknown), ", ".join(sorted(known))))
    selected = [scene for scene in scenes if not wanted or scene.id in wanted]

    frame = theme.frame
    for scene in selected:
        for capture in scene.captures:
            path = raw_dir / (capture + ".png")
            expect(path.is_file(), "scene %s needs %s, which does not exist; capture it or drop it into %s" % (
                scene.id, path.name, raw_dir))
            width, height, _, _, _ = png_info(path)
            expect((width, height) == (frame.screen_width, frame.screen_height),
                   "%s is %dx%d; the %s frame takes %dx%d captures" % (
                       path.name, width, height, frame.directory.name, frame.screen_width, frame.screen_height))

    work_dir.mkdir(parents=True, exist_ok=True)
    out_dir.mkdir(parents=True, exist_ok=True)
    profile_dir = work_dir / "chrome-profile"
    for scene in selected:
        page = work_dir / (scene.id + ".html")
        page.write_text(build_page(scene, theme, raw_dir, template, style), encoding="utf-8")
        rendered = work_dir / scene.output_name
        rasterise(chrome, page, rendered, theme, profile_dir)
        _, _, _, colour, _ = png_info(rendered)
        if colour == PNG_RGBA:
            stripped = work_dir / ("rgb-" + scene.output_name)
            strip_alpha(rendered, stripped)
            rendered = stripped
        verify_store_image(rendered, theme)
        target = out_dir / scene.output_name
        shutil.copyfile(rendered, target)
        width, height, _, _, _ = png_info(target)
        print("%-28s %dx%d RGB %4d KB  %s" % (target.name, width, height, target.stat().st_size // 1024, scene.layout_name))

    # In every mode: the expected set is the whole scene list, so this only ever deletes files
    # whose number or id is no longer in it, such as 02-first.png after a reorder.
    remove_stale_outputs(out_dir, {scene.output_name for scene in scenes})
    missing = [scene.output_name for scene in scenes if not (out_dir / scene.output_name).is_file()]
    if missing:
        print("README and preview not written: %s not rendered yet" % ", ".join(missing))
        return
    if args.readme != "-":
        readme_path = resolve(args.readme)
        changed = update_readme(readme_path, readme_block(scenes, out_dir, readme_path))
        print("%s block %s" % (readme_path.name, "updated" if changed else "unchanged"))
    if args.preview != "-":
        preview_path = resolve(args.preview)
        preview_page(scenes, theme, raw_dir, out_dir, preview_path)
        print("review page: %s" % preview_path)


def main(argv=None):
    args = parse_args(sys.argv[1:] if argv is None else argv)
    try:
        run(args)
    except RenderError as error:
        print("error: %s" % error, file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
