name: PR Agent (Gemini)
on:
  pull_request:
    types: [ opened, reopened, ready_for_review, synchronize ]
  issue_comment:
    types: [ created, edited ]
jobs:
  pr_agent_job:
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: PR Agent action step
        uses: the-pr-agent/pr-agent@5a7b6a4a1b02b55f10bbcfb22b72ee025b34a621 # main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          config.model: "gemini/gemini-3.5-flash"
          config.fallback_models: '["gemini/gemini-1.5-flash", "gemini/gemini-2.0-pro-exp"]'
          config.restricted_mode: "true"
          GOOGLE_AI_STUDIO.GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          github_action_config.auto_review: "true"
          github_action_config.auto_describe: "true"
          github_action_config.auto_improve: "true"
          github_action_config.handle_push_trigger: "true"
          github_action_config.push_commands: '["/review"]'